### ISSUE TITLE
naueo

### ISSUE THREAD

**Issue by brianamarie** [brianamarie/travel-log#8]

**Comment by brianamarie** [comment]
comment

**Comment by brianamarie** [comment]
afafa

**Comment by githubteacher** [comment]
o hai

**Comment by githubteacher** [comment]
hello

**Comment by githubteacher** [comment]
hihihi

**Comment by githubteacher** [comment]
gaef

**Comment by brianamarie** [comment]
afaf

**Comment by brianamarie** [comment]
asdf

**Comment by githubteacher** [comment]
asfd

**Comment by githubteacher** [comment]
hallo

**Comment by githubteacher** [comment]
gafa

**Comment by githubteacher** [comment]
afaf

**Comment by githubteacher** [comment]
sdf

**Comment by githubteacher** [comment]
afed

**Comment by githubteacher** [comment]
loop

**Comment by githubteacher** [comment]
baf

**Comment by githubteacher** [comment]
lala

**Comment by githubteacher** [comment]
momo

**Comment by githubteacher** [comment]
gomefn

**Comment by githubteacher** [comment]
hallo

**Comment by hectorsector** [comment]
hallo!

**Comment by hectorsector** [comment]
hia

**Comment by brianamarie** [comment]
```
[2016-09-07 15:48:38] INFO  WEBrick 1.3.1
[2016-09-07 15:48:38] INFO  ruby 2.3.0 (2015-12-25) [x86_64-darwin15]
== Sinatra (v1.4.7) has taken the stage on 4567 for development with backup from WEBrick
[2016-09-07 15:48:38] INFO  WEBrick::HTTPServer#start: pid=41025 port=4567
Testing 123 Amazing
{:repo_name=>"brianamarie/travel-log", :issue_num=>8}
/usr/local/lib/ruby/gems/2.3.0/gems/octokit-4.3.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/repos/brianamarie/travel-log/collaborators?per_page=100: 403 - Must have push access to view repository collaborators. // See: https://developer.github.com/v3 (Octokit::Forbidden)
    from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
    from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
    from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
    from /usr/local/lib/ruby/gems/2.3.0/gems/octokit-4.3.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
    from /usr/local/lib/ruby/gems/2.3.0/gems/octokit-4.3.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
    from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
    from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
    from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
    from /usr/local/lib/ruby/gems/2.3.0/gems/sawyer-0.7.0/lib/sawyer/agent.rb:94:in `call'
    from /usr/local/lib/ruby/gems/2.3.0/gems/octokit-4.3.0/lib/octokit/connection.rb:154:in `request'
    from /usr/local/lib/ruby/gems/2.3.0/gems/octokit-4.3.0/lib/octokit/connection.rb:84:in `paginate'
    from /usr/local/lib/ruby/gems/2.3.0/gems/octokit-4.3.0/lib/octokit/client/repositories.rb:288:in `collaborators'
    from ./addcollaborators:44:in `<main>'
```

**Comment by brianamarie** [comment]
```
/usr/local/lib/ruby/gems/2.3.0/gems/octokit-4.3.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/repos/brianamarie/travel-log/collaborators?per_page=100: 403 - Must have push access to view repository collaborators. // See: https://developer.github.com/v3 (Octokit::Forbidden)
```

**Comment by hectorsector** [comment]
asfsf

**Comment by brianamarie** [comment]
Failed to add hectorsector as a collaborator (check: is githubteacher repository owner?)
Failed to add hectorsector as a collaborator (check: is githubteacher repository owner?)
Failed to add hectorsector as a collaborator (check: is githubteacher repository owner?)
